version: '3.8'

services:
  api:
    image: countries_api:latest
    depends_on:
      - db
    ports:
      - target: 3000
        published: 3000
        mode: host
    environment:
      - NODE_ENV=development
      - TZ="Europe/Samara"
    env_file:
      - '.env'
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
